name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  crash_with_efcore_using_plain_connection_string:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run db
      run: docker compose up -d
    - name: Run project
      run: cd CAPPostgres && dotnet run --ConnectionStrings:PostgresConnection "User ID=postgres;Password=admin;Server=127.0.0.1;Port=5432;Database=cap_db;Persist Security Info=true"

  works_correct_with_efcore_using_connection_string_with_insecure_parameter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run db
      run: docker compose up -d
    - name: Run project
      run: cd CAPPostgres && dotnet run --ConnectionStrings:PostgresConnection "User ID=postgres;Password=admin;Server=127.0.0.1;Port=5432;Database=cap_db;Persist Security Info=true"